[globals]

[[input]]
name = "metrics"
type = "metrics"
[input.args]
disk_poll_secs = 5

[[transform]]
name = "insert_ts"
type = "insert_ts"
[transform.args]
field = "t"

# Outputs
[[output]]
name = "stdout"
type = "stdout"

# Routes
[[route]]
name = "test"
input = "metrics"
transforms = ["insert_ts"]
output = "stdout"



