#!/bin/bash

set -e

# add log-ship to adm group to read /var/logs
usermod --append --groups adm log-ship || true

# add log-ship to systemd-journal to read journald logs
if getent group 'systemd-journal'
then
  usermod --append --groups systemd-journal log-ship || true
  systemctl daemon-reload || true
fi

#DEBHELPER#
